name: Build images for Docker Hub
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [base-container-updated]

env:
  REPO: "owasp/modsecurity-crs"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        crs_version: ["3.3.5"]
        image: [apache, nginx]
        variant: ["", "-alpine"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:master

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.dockerhub_user }}
          password: ${{ secrets.dockerhub_token }}

      - name: Docker meta ${{ matrix.crs_version }}-${{ matrix.image }}${{ matrix.variant }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REPO }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ matrix.image }}${{ matrix.variant }}
            type=semver,pattern={{major}},value=v${{ matrix.crs_version }},suffix=${{ matrix.image }}${{ matrix.variant }}-{{date 'YYYYMMDDHHMM'}}
            type=semver,pattern={{major}}.{{minor}},value=v${{ matrix.crs_version }},suffix=${{ matrix.image }}${{ matrix.variant }}-{{date 'YYYYMMDDHHMM'}}
            type=semver,pattern={{version}},value=v${{ matrix.crs_version }},suffix=${{ matrix.image }}${{ matrix.variant }}-{{date 'YYYYMMDDHHMM'}}

      - name: Build and push ${{ matrix.crs_version }}-${{ matrix.image }}${{ matrix.variant }}
        uses: docker/bake-action@v2.3.0
        with:
          targets: ${{ matrix.image }}${{ matrix.variant }}
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          push: true
